<?php
	
	error_reporting(E_ALL);
	ini_set("display_errors", "on");
	
	require 'facebook/facebook.php';

	$metric = $_GET['metric'];
	
	// Create our Application instance.
	$facebook = new Facebook(array(
		'appId'  => '239066989437628',
		'secret' => '1e42bcc9eefab1699cc25c201c246bd6'
	));

	// If we get a $user id here, it means we know the user is logged 
	// into Facebook, but we don’t know if the access token is valid.
	$user = $facebook->getUser();
	if ($user) {
		
		/* Make the API-call
		Friends: https://graph.facebook.com/me/friends?access_token=...
	    News feed: https://graph.facebook.com/me/home?access_token=...
	    Profile feed (Wall): https://graph.facebook.com/me/feed?access_token=...
	    Likes: https://graph.facebook.com/me/likes?access_token=...
	    Movies: https://graph.facebook.com/me/movies?access_token=...
	    Music: https://graph.facebook.com/me/music?access_token=...
	    Books: https://graph.facebook.com/me/books?access_token=...
	    Notes: https://graph.facebook.com/me/notes?access_token=...
	    Permissions: https://graph.facebook.com/me/permissions?access_token=...
	    Photo Tags: https://graph.facebook.com/me/photos?access_token=...
	    Photo Albums: https://graph.facebook.com/me/albums?access_token=...
	    Video Tags: https://graph.facebook.com/me/videos?access_token=...
	    Video Uploads: https://graph.facebook.com/me/videos/uploaded?access_token=...
	    Events: https://graph.facebook.com/me/events?access_token=...
	    Groups: https://graph.facebook.com/me/groups?access_token=...
	    Checkins: https://graph.facebook.com/me/checkins?access_token=...
	    */
		$url = '/me/' . $metric;
		$data = $facebook->api($url);
	} else {
		$data = 0;
	}
		
	echo json_encode($data);
?>



